# Generated by Django 6.1.2 on 2026-10-09 05:24

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=accounts.models.new_invite_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, help_text="Who this invite is for.", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "used_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "used_by",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
