# Generated by Django 6.1.2 on 2026-10-09 05:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "multiple",
                    models.PositiveIntegerField(
                        help_text='N in "multiple of N + M": the number of stitches in one repeat.',
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "edge_stitches",
                    models.PositiveIntegerField(
                        default=0,
                        help_text='M in "multiple of N + M". Enter only the extra stitches that appear in every row. Turning chains never count as stitches here, so if the pattern\'s M includes a turning chain, leave it out.',
                    ),
                ),
                (
                    "colors",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2")],
                        default=1,
                        help_text="A two-color stitch needs two different colors per draw.",
                    ),
                ),
                (
                    "source",
                    models.URLField(
                        blank=True, help_text="The URL the stitch data came from."
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="stitches/")),
                ("is_public", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
