# Generated by Django 6.1.2 on 2026-10-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stitches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stitch",
            name="instructions",
            field=models.TextField(blank=True, help_text="How to work the stitch."),
        ),
    ]
