# Generated by Django 6.1.2 on 2026-10-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stitches", "0002_stitch_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="stitch",
            name="photo_credit",
            field=models.CharField(
                blank=True,
                help_text="Who took the photo and its license, if it isn't yours. Links are clickable.",
                max_length=500,
            ),
        ),
    ]
