# Generated by Django 6.1.2 on 2026-10-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcolor",
            name="yarn_url",
            field=models.URLField(
                blank=True,
                help_text="Optional link to the yarn's product page.",
                verbose_name="yarn link",
            ),
        ),
    ]
