# Generated by Django 6.1.2 on 2026-10-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_color_yarn_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="repeat_gap",
            field=models.PositiveIntegerField(
                verbose_name="draws to skip a picked stitch or color"
            ),
        ),
    ]
