# Generated by Django 6.1.2 on 2026-10-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_color_yarn_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="repeat_gap",
            field=models.PositiveIntegerField(
                help_text="A stitch or color used in any of this many latest draws can't be drawn. 0 allows back-to-back repeats.",
                verbose_name="draws before a repeat",
            ),
        ),
    ]
